services:
  db:
    container_name: mysql_db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${BDROOTPASS}
      MYSQL_PASSWORD: ${DBPASS}
      MYSQL_DATABASE: ${DBNAME}
      MYSQL_USER: ${DBUSER}
      MYSQL_PORT: ${DBPORT}
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    command: --init-file /docker-entrypoint-initdb.d/backup.sql

volumes:
  db_data:
